apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: app: prometheus-service
  namespace: kube-system
spec:
  selector:
    app: prometheus
  ports:
  - port: 80
    targetPort: 9090