name: Build and Publish the Docker Image

on: 
  release:
    types: [created]
jobs:
  build_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd api
          echo ${{ env.VERSION }}
          docker build -t wxapi:${{ env.VERSION }} .
      - name: Publish
        run: |
          docker login -u shafatjamil -p ${{ secrets.DOCKER_HUB_PAT }}
          docker tag wxapi:${{ env.VERSION }} shafatjamil/wxapi:${{ env.VERSION }}
          docker push shafatjamil/wxapi:${{ env.VERSION }}